[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"


[project]
name = "boltzmann"
version = "0.1.0"
requires-python = ">=3.10"


[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]

[tool.ruff]
line-length = 100
