[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "boltzmann"
version = "0.1.1"
dependencies = [
    "numpy",
    "numba",
    "matplotlib"
]

# [tool.ruff.lint]
# select = ["ALL"]

[tool.ruff]
line-length = 100